# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'juqi' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks! :linkage => :static
  use_modular_headers!

  # Pods for juqi
  pod 'WechatOpenSDK'

end